# There is some available configurations in YaSSOS
spring:
  # required when 'yassos.session-manager.type=redis'
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  # required when 'yassos.user-store.type=jdbc'
  datasource:
    username: test
    password: '!@#$%^^%$#@!'
    url: jdbc:mysql://localhost:3306/yassos_server?useUnicode=true&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
yassos:
  session-manager:
    type: memory
    idle-time: 30m
    redis:
      key-prefix: 'yassos_session:'
  user-store:
    type: file
    file:
      file-location: classpath:file-user-store.json
    jdbc:
      sql-to-load-user-details: 'select id as userId, name as username, password, locked, credential_expired, avatarUrl from yassos_user where name = ?'
  client-cookie:
    enabled: true
    http-only: false
    secure: false
    path: /
    max-age: 40m
    name: x-yassos-token
    domain: .mine.com


