server:
  port: 9000
  servlet:
    context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
yassos:
  session:
    idle-time: 10m
    redis:
      key-prefix: 'yassos_session:'