server:
  port: 9000
  servlet:
    context-path: /
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
yassos:
  session:
    type: redis
    idle-time: 30m
    redis:
      key-prefix: 'yassos_session:'
  cookie:
    enabled: true
    http-only: false
    secure: false
    path: /
    max-age: 40m
    name: x-yassos-token
    domain: .mine.com
