server:
  port: 5201
  servlet:
    context-path: /
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  output:
    ansi:
      enabled: detect
  datasource:
    username: test
    password: '!@#$%^^%$#@!'
    url: jdbc:mysql://node1:3306/yassos_server?useUnicode=true&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: i18n.login,i18n.login-sucess
  banner:
    location: yassos-banner.txt
  main:
    banner-mode: log
yassos:
  session:
    type: memory
    idle-time: 30m
    redis:
      key-prefix: 'yassos_session:'
  cookie:
    enabled: true
    http-only: false
    secure: false
    path: /
    max-age: 40m
    name: x-yassos-token
    domain: .mine.com
logging:
  config: classpath:logback.xml

